### PR TITLE
Add unit tests for all implemented methods.

### PR DESCRIPTION
**Pull request by chudisoft**
**The following options should be available:**

-List all books
-List all labels (e.g. 'Gift', 'New')

    Add a book

**can_be_archived?() in the Book class**

    should override the method from the parent class
    should return true if parent's method returns true OR if cover_state equals to "bad"
    otherwise, it should return false

**Add unit tests for all implemented methods in the label class.**

### CODE REVIEW

**Comment by arnoldnekemiah** [comment]
@chudisoft , The tests are failing

**Comment by chudisoft** [comment]
@arnoldnekemiah kindly check again

**Review by arnoldnekemiah — CHANGES_REQUESTED** [review]
Hi @chudisoft ,
You have done well implementing all methods in the Label class but there some remaining requirements you need to satisfy;


### **Required Changes** :recycle: :recycle: 


You have not completed the task of implementing tests for all methods as shown below

image

Also I have noticed the Book class has a missing method which will also need to feature in the tests, surely you missed out on a card.

image

**Review by arnoldnekemiah — APPROVED** [review]
Hi @chudisoft    👏 👏 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Added all tests

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
